package net.badbird5907.generator;

import static com.formdev.flatlaf.IntelliJTheme.setup;
import static com.intellij.uiDesigner.core.GridConstraints.*;
import static java.awt.Toolkit.getDefaultToolkit;
import static java.lang.String.valueOf;
import static java.lang.System.err;
import static java.lang.System.out;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

import java.awt.Dimension;
import java.awt.Insets;
import java.awt.datatransfer.StringSelection;
import java.io.InputStream;
import java.text.ParseException;

import javax.swing.*;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import lombok.Getter;

public class MainGUI {
    private static final String BASE = "/data merge entity %id% {Offers:{Recipes:[{buy:{id:%buyid%,Count:%buycount%},sell:{id:emerald,Count:1},maxUses:9999999},{buy:{id:emerald,Count:%price%},buyB:{id:book,Count:1},sell:{id:enchanted_book,Count:1,tag:{StoredEnchantments:[{id:%enchant%,lvl:%level%}]}},maxUses:9999999}]}}";

    public static void main(String[] args) {
        InputStream stream = MainGUI.class.getClassLoader().getResourceAsStream("XCodeDark.theme.json");
        if (stream == null)
            err.println("Stream is null");
        else
            setup(stream);
        frame = new JFrame("Command Utils");
        INSTANCE = new MainGUI();
        frame.setContentPane(INSTANCE.panel1);
        frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
        frame.setSize(350, 420);
        frame.pack();
        frame.setVisible(true);
        INSTANCE.goButton.addActionListener(e -> {
            try {
                INSTANCE.buyAmount.commitEdit();
                INSTANCE.enchantLevel.commitEdit();
                INSTANCE.price.commitEdit();
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
            String s = BASE.replace("%id%", INSTANCE.villagerId.getText()).replace("%buyid%", INSTANCE.buy.getText())
                    .replace("%buycount%", valueOf(INSTANCE.buyAmount.getValue()))
                    .replace("%enchant%", INSTANCE.enchant.getText())
                    .replace("%level%", valueOf(INSTANCE.enchantLevel.getValue()))
                    .replace("%price%", valueOf(INSTANCE.price.getValue()));
            out.println(s);
            getDefaultToolkit().getSystemClipboard().setContents(new StringSelection(s), null);
            showMessageDialog(null, "Command has been copied to your clipboard:\n" + s);
        });
    }

    @Getter
    private static MainGUI INSTANCE;
    @Getter
    private static JFrame frame;
    private JTabbedPane mainPane;
    private JPanel panel1;
    private JButton goButton;
    private JTextField villagerId;
    private JTextField buy;
    private JSpinner buyAmount;
    private JTextField enchant;
    private JSpinner enchantLevel;
    private JSpinner price;

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT
     * edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPane = new JTabbedPane();
        panel1.add(mainPane,
                new GridConstraints(0, 0, 1, 1, ANCHOR_CENTER, FILL_BOTH, SIZEPOLICY_CAN_SHRINK | SIZEPOLICY_CAN_GROW,
                        SIZEPOLICY_CAN_SHRINK | SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(6, 6, new Insets(0, 0, 0, 0), -1, -1));
        mainPane.addTab("Librarian Enchant", panel2);
        goButton = new JButton();
        goButton.setText("Go!");
        panel2.add(goButton, new GridConstraints(5, 0, 1, 6, ANCHOR_CENTER, FILL_HORIZONTAL,
                SIZEPOLICY_CAN_SHRINK | SIZEPOLICY_CAN_GROW, SIZEPOLICY_FIXED, null, null, null, 0, false));
        villagerId = new JTextField();
        villagerId.setText("Villager ID");
        panel2.add(villagerId, new GridConstraints(0, 0, 1, 6, ANCHOR_WEST, FILL_HORIZONTAL, SIZEPOLICY_WANT_GROW,
                SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(4, 0, 1, 1, ANCHOR_CENTER, FILL_VERTICAL, 1, SIZEPOLICY_WANT_GROW, null,
                null, null, 0, false));
        buyAmount = new JSpinner();
        panel2.add(buyAmount, new GridConstraints(1, 5, 1, 1, ANCHOR_WEST, FILL_HORIZONTAL, SIZEPOLICY_WANT_GROW,
                SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel2.add(spacer2, new GridConstraints(1, 4, 1, 1, ANCHOR_CENTER, FILL_HORIZONTAL, SIZEPOLICY_WANT_GROW, 1,
                null, null, null, 0, false));
        enchant = new JTextField();
        enchant.setText("Enchant");
        panel2.add(enchant, new GridConstraints(2, 0, 1, 4, ANCHOR_WEST, FILL_HORIZONTAL, SIZEPOLICY_WANT_GROW,
                SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        enchantLevel = new JSpinner();
        panel2.add(enchantLevel, new GridConstraints(2, 5, 1, 1, ANCHOR_WEST, FILL_HORIZONTAL, SIZEPOLICY_WANT_GROW,
                SIZEPOLICY_FIXED, null, null, null, 0, false));
        buy = new JTextField();
        buy.setText("Item to buy Per emerald");
        panel2.add(buy, new GridConstraints(1, 0, 1, 4, ANCHOR_WEST, FILL_HORIZONTAL, SIZEPOLICY_WANT_GROW,
                SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        price = new JSpinner();
        panel2.add(price, new GridConstraints(3, 0, 1, 6, ANCHOR_WEST, FILL_HORIZONTAL, SIZEPOLICY_WANT_GROW,
                SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
